#+TAGS: REFERENCE(r) DROPBOX(d) CALIBRE(c) FULLBIB(f)
#+TODO: TOADD | DONE
#+TODO: TOREAD | DONE

* On the Atiyah-Hitchin-Drinfeld-Manin Vanishing Theorem for Cohomology Groups of Instanton Bundles :FULLBIB:REFERENCE:DROPBOX:
[2016-05-20 ven. 09:35]
** Author 
   J. H. Rawnsley
** Liens
   Dropbox
** Sujet
   Expression en coordonnées de la fibration twistorielle $\Pro^3 \to \S^4$

* TOADD Eastwood : Some remarks on nonabelian sheaf cohomology :REFERENCE:CALIBRE:FULLBIB:
[2016-06-06 lun. 17:47]

- Introuvable en ligne
- Regarder à la BU

- [X] full
- [ ] Calibre
- [ ] Dwl (IRMAR)

Type: 	Book chapter
Title: 	Some remarks on non-Abelian sheaf cohomology
Author: 	Eastwood, Michael George
Citation: 	Further advances in twistor theory. Vol. III, Curved twistor spaces / L.J. Mason, L.P. Hughston, P.Z. Kobak, and K. Pulverer (eds.), pp. 113-115
Publisher: 	Chapman & Hall / CRC
Issue Date: 	2001
Series/Report no.: 	Chapman & Hall/CRC research notes in mathematics series ; 424
ISBN: 	1584880473
School/Discipline: 	School of Mathematical Sciences : Pure Mathematics
RMID: 	0020073282
Description (link): 	http://trove.nla.gov.au/work/34692578
Appears in Collections:	Pure Mathematics publications


#+BEGIN_SRC bibtex
@book{1584880473,
  Author = {},
  Title = {Further Advances in Twistor Theory, Volume III: Curved Twistor Spaces},
  Publisher = {Chapman and Hall/CRC},
  Year = {2001},
  ISBN = {1584880473},
  URL = {http://www.amazon.com/Further-Advances-Twistor-Theory-III/dp/1584880473%3FSubscriptionId%3D0JYN1NVW651KCA56C102%26tag%3Dtechkie-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3D1584880473}
}
@chapter{
}

#+END_SRC

* DONE Kodaira : Completude family submanifolds  [2/2] :REFERENCE:CALIBRE:FULLBIB:ARCHIVE:
- [X] full
- [X] calibre

* Campana cycles compacts                                           :ARCHIVE:

** DONE [3/3]  Espaces de twisteurs dont l'espace des cycles a ses composantes irréductibles compactes :REFERENCE:CALIBRE:FULLBIB:
 [2016-07-06 mer. 11:54]

 - [X] full
 - [X] calibre
 - [X] Téléchargé (Irmar)

 *Ne traite pas directement du cas hyperkahlérien*
 
 #+BEGIN_SRC BIBTEX
 @article {MR999456,
     AUTHOR = {Campana, Fr{\'e}d{\'e}ric},
      TITLE = {Espaces de twisteurs dont l'espace des cycles a ses
               composantes irr\'eductibles compactes},
    JOURNAL = {C. R. Acad. Sci. Paris S\'er. I Math.},
   FJOURNAL = {Comptes Rendus des S\'eances de l'Acad\'emie des Sciences.
               S\'erie I. Math\'ematique},
     VOLUME = {308},
       YEAR = {1989},
     NUMBER = {19},
      PAGES = {565--568},
       ISSN = {0249-6291},
      CODEN = {CASMEI},
    MRCLASS = {32G10 (32J10 32L25 53C21)},
   MRNUMBER = {999456},
 }
 #+END_SRC

** DONE [3/3] Espace des twisteurs de classe $C$                  :REFERENCE:
 [2016-07-06 mer. 18:22]


 - [X] full
 - [X] calibre
 - [X] Téléchargé (Irmar)

 Il prouve que $C$ n'est jamais compact. (Compact entraine $Z$ de classe C entraine $M$ conformément plate entraine $M$ sphère ou somme connexe de plans projectifs)

 #+BEGIN_SRC BIBTEX
 @article {MR1094468,
     AUTHOR = {Campana, F.},
      TITLE = {On twistor spaces of the class {$\scr C$}},
    JOURNAL = {J. Differential Geom.},
   FJOURNAL = {Journal of Differential Geometry},
     VOLUME = {33},
       YEAR = {1991},
     NUMBER = {2},
      PAGES = {541--549},
       ISSN = {0022-040X},
      CODEN = {JDGEAS},
    MRCLASS = {32L25 (32J20 53C25)},
   MRNUMBER = {1094468},
 MRREVIEWER = {S. M. Salamon},
        URL = {http://projecteuclid.org/euclid.jdg/1214446329},
 }
 #+END_SRC


** DONE [3/3] Cycle Spaces, Several complex variables VII         :REFERENCE:
 [2016-07-06 mer. 12:03]

 - [X] full
 - [X] calibre
 - [X] Téléchargé (Irmar)


 #+BEGIN_SRC BIBTEX
 @incollection {MR1326625,
     AUTHOR = {Campana, F. and Peternell, Th.},
      TITLE = {Cycle spaces},
  BOOKTITLE = {Several complex variables, {VII}},
     SERIES = {Encyclopaedia Math. Sci.},
     VOLUME = {74},
      PAGES = {319--349},
  PUBLISHER = {Springer, Berlin},
       YEAR = {1994},
    MRCLASS = {32G10 (32F10)},
   MRNUMBER = {1326625},
        DOI = {10.1007/978-3-662-09873-8_9},
        URL = {http://dx.doi.org/10.1007/978-3-662-09873-8_9},
 }
 #+END_SRC

* TOADD [1/3] Thèse de Guillaume Deschamps           :REFERENCE:
[2016-07-19 mar. 22:53]

- [X] full
- [ ] calibre
- [ ] dwl (Irmar)

* DONE [2/2] Lawson Michelsohn /Spin Geometry/            :REFERENCE:ARCHIVE:
[2016-07-04 lun. 18:03]

- [X] full
- [X] calibre

* TOADD [0/0] EASTWOOD : De Rham symplectique                     :REFERENCE:
[2016-07-07 jeu. 12:27]

- [ ] full
- [ ] calibre
- [ ] Téléchargé (IRMAR) ?

** Blabla

Le complexe de DR sur une variété symplectique réelle se découpe en 2 complexes de taille $n$, qu'on recolle par un opérateur différentiel d'ordre $2$.

** Eastwood Slovàk

MR2103078 Reviewed Eastwood, Michael; Slovák, Jan Preferred parameterisations on homogeneous curves. Comment. Math. Univ. Carolin. 45 (2004), no. 4, 597–606. (Reviewer: A. Rod Gover) 53C30 (17B66)
PDF Clipboard Journal Article

MR1483772 Reviewed Eastwood, Michael; Slovák, Jan Semiholonomic Verma modules. J. Algebra 197 (1997), no. 2, 424–448. (Reviewer: William M. McGovern) 22E46 (17B35)
PDF Clipboard Journal Article 

** Eastwood Goldschmidt

#+BEGIN_SRC BIBTEX
@article {MR3031862,
    AUTHOR = {Eastwood, Michael and Goldschmidt, Hubert},
     TITLE = {Zero-energy fields on complex projective space},
   JOURNAL = {J. Differential Geom.},
  FJOURNAL = {Journal of Differential Geometry},
    VOLUME = {94},
      YEAR = {2013},
    NUMBER = {1},
     PAGES = {129--157},
      ISSN = {0022-040X},
     CODEN = {JDGEAS},
   MRCLASS = {53C65 (32C38 44A12 53C22 53C55 58J10)},
  MRNUMBER = {3031862},
MRREVIEWER = {Andreas Cap},
       URL = {http://projecteuclid.org/euclid.jdg/1361889063},
}
#+END_SRC

* TOREAD BEAUVILLE : Holomorphic symplectic geometry: a problem list :READ:REFERENCE:
[2016-07-11 lun. 11:27]

http://arxiv.org/abs/1002.4321

- Partie sur les structures de contact, lien avec Honda : fibré fondamental


* DONE [3/3] Le Brun : Thickenings                        :REFERENCE:ARCHIVE:
[2016-08-12 ven. 15:16]

- [X] full
- [X] calibre
- [X] dwl (Irmar)

#+BEGIN_SRC bibtex
@article {MR859775,
    AUTHOR = {Eastwood, Michael and LeBrun, Claude},
     TITLE = {Thickening and supersymmetric extensions of complex manifolds},
   JOURNAL = {Amer. J. Math.},
  FJOURNAL = {American Journal of Mathematics},
    VOLUME = {108},
      YEAR = {1986},
    NUMBER = {5},
     PAGES = {1177--1192},
      ISSN = {0002-9327},
     CODEN = {AJMAAN},
   MRCLASS = {32D15 (32C15 32L25)},
  MRNUMBER = {859775},
MRREVIEWER = {Nicholas Buchdahl},
       DOI = {10.2307/2374601},
       URL = {http://dx.doi.org/10.2307/2374601},
}
#+END_SRC

* DONE [3/3] Mumford : Abelian varieties                  :REFERENCE:ARCHIVE:
   [2016-08-16 mar. 08:40]


- [X] full
- [X] calibre
- [X] dwl (Irmar)

Formule de la projection et "changement de base"
#+begin_src bibtex
@book{MumfordAV,
  Author = {David Mumford},
  Title = {Abelian Varieties (Tata Institute of Fundamental Research)},
  Publisher = {Amer Mathematical Society},
  Year = {2012},
  ISBN = {8185931860}
}
#+end_src

* TOREAD Relative Frolicher spectral sequence :SuiteSpectrale:Frolicher::REFERENCE:
[2016-08-29 lun. 19:04]

Application à l'étude de la suite spectrale de Fro relative sur $Z$.

** /Period mappings with applications to symplectic complex spaces/ 
(http://cds.cern.ch/record/2112887?ln=bg) 

((pas terrible, parle du cas singulier))

#+BEGIN_QUOTE
The second part investigates the degeneration behavior of the relative Frölicher spectral sequence associated to a submersive morphism of complex manifolds.
#+END_QUOTE

** /Mixed Hodge Structures/ Chap 10.4, Prop 10.29

   #+BEGIN_SRC BIBTEX
@book{9783540770152,
  Author = {Christiaan Peters and Joseph H. M. Steenbrink},
  Title = {Mixed Hodge Structures (Ergebnisse der Mathematik und ihrer Grenzgebiete. 3. Folge / A Series of Modern Surveys in Mathematics)},
  Publisher = {Springer},
  Year = {2008},
  ISBN = {3540770151},
  URL = {http://www.amazon.com/Structures-Ergebnisse-Mathematik-Grenzgebiete-Mathematics/dp/3540770151%3FSubscriptionId%3D0JYN1NVW651KCA56C102%26tag%3Dtechkie-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3D3540770151}
}
   #+END_SRC BIBTEX

- [X] full
- [ ] calibre
- [ ] dwl (Irmar)
- [X] dwl (Windu)

* TOREAD  Algebraic Cycles and Homotopy Theory by H. Blaine Lawson, Jr.  :REFERENCE:
[2016-11-01 mar. 10:38]


/Algebraic Cycles and Homotopy Theory/
H. Blaine Lawson, Jr.
Annals of Mathematics
Second Series, Vol. 129, No. 2 (Mar., 1989), pp. 253-291
Published by: Annals of Mathematics
DOI: 10.2307/1971448
Stable URL: http://www.jstor.org/stable/1971448
Page Count: 39

#+BEGIN_SRC bibtex
@article{LawsonCyclesHomotopy,
 ISSN = {0003486X},
 URL = {http://www.jstor.org/stable/1971448},
 author = {H. Blaine Lawson},
 journal = {Annals of Mathematics},
 number = {2},
 pages = {253-291},
 publisher = {Annals of Mathematics},
 title = {Algebraic Cycles and Homotopy Theory},
 volume = {129},
 year = {1989}
}
#+END_SRC

* TOREAD S. Akbulut 4-Manifolds                                   :REFERENCE:
[2016-11-07 lun. 15:36]

http://users.math.msu.edu/users/akbulut/

* TOREAD [#A] Correspondence and cycle spaces: A result comparing their cohomologies :REFERENCE:
[2016-12-06 mar. 08:58]

https://publications.ias.edu/node/2635

- [ ] DWL yoda
- [ ] full.bib
- [ ] 

* TOREAD [#A] Special values of automorphic cohomology classes    :REFERENCE:
[2016-12-06 mar. 09:00]


Mark Green, Phillip Griffiths and Matt Kerr

Publication: Memoirs of the American Mathematical Society
Publication Year: 2014; Volume 231, Number 1088
ISBNs: 978-0-8218-9857-4 (print); 978-1-4704-1724-6 (online)
DOI: http://dx.doi.org/10.1090/memo/1088
Published electronically: February 19, 2014
Keywords:Mumford-Tate group, automorphic cohomology, Mumford-Tate domain, CM point, homogeneous complex manifold, Lagrange quadrilateral, homogeneous line bundle, correspondence space, cycle space, Stein manifold, Penrose transform, coherent cohomology, Picard and Siegel automorphic forms, automorphic cohomology, cuspidal automorphic cohomology, discrete series, Lie algebra cohomology, K-type 


Table of Contents

Chapters

    Introduction
    Chapter 1. Geometry of the Mumford-Tate domains
    Chapter 2. Homogeneous line bundles over the Mumford-Tate domains
    Chapter 3. Correspondence and cycle spaces; Penrose transforms
    Chapter 4. The Penrose transform in the automorphic case and the main result 

Abstract

We study the complex geometry and coherent cohomology of nonclassicalMumford-Tate domains and their quotients by discrete groups. Our focus throughout is on the domains D which occur as open G(R)-orbits in the flag varieties for G=SU(2,1) and Sp(4), regarded as classifying spaces for Hodge structures of weight three. In the context provided by these basic examples, we formulate and illustrate the general method by which correspondence spaces W give rise to Penrose transforms between the cohomologies Hq(D,L) of distinct such orbits with coefficients in homogeneous line bundles. Turning to the quotients, representation theory allows us to define subspaces of Hq(Γ∖D,L) called cuspidal automorphic cohomology, which via the Penrose transform are endowed in some cases with an arithmetic structure. We demonstrate that the arithmetic classes assume arithmetic values at CM points in W, up to a transcendental factor that depends only on the CM type. The representations related to this result are certain holomorphic discrete series representations of G(R). We conclude with a discussion of how our framework may also be used to study the K-types and n-cohomology of (non-holomorphic) totally degenerate limits of discrete series, and to give an alternative treatment of the main result of Carayol (1998). These especially interesting connections will be further developed in future works. 

