#+TAGS: REFERENCE(r) DROPBOX(d) CALIBRE(c) FULLBIB(f)

* On the Atiyah-Hitchin-Drinfeld-Manin Vanishing Theorem for Cohomology Groups of Instanton Bundles :FULLBIB:REFERENCE:DROPBOX:
[2016-05-20 ven. 09:35]
** Author 
   J. H. Rawnsley
** Liens
   Dropbox
** Sujet
   Expression en coordonnées de la fibration twistorielle $\Pro^3 \to \S^4$

* TODO Eastwood : Some remarks on nonabelian sheaf cohomology :REFERENCE:CALIBRE:FULLBIB:
[2016-06-06 lun. 17:47]

- Introuvable en ligne
- Regarder à la BU

Type: 	Book chapter
Title: 	Some remarks on non-Abelian sheaf cohomology
Author: 	Eastwood, Michael George
Citation: 	Further advances in twistor theory. Vol. III, Curved twistor spaces / L.J. Mason, L.P. Hughston, P.Z. Kobak, and K. Pulverer (eds.), pp. 113-115
Publisher: 	Chapman & Hall / CRC
Issue Date: 	2001
Series/Report no.: 	Chapman & Hall/CRC research notes in mathematics series ; 424
ISBN: 	1584880473
School/Discipline: 	School of Mathematical Sciences : Pure Mathematics
RMID: 	0020073282
Description (link): 	http://trove.nla.gov.au/work/34692578
Appears in Collections:	Pure Mathematics publications


* DONE Kodaira : Completude family submanifolds  [2/2] :REFERENCE:CALIBRE:FULLBIB:ARCHIVE:
- [X] full
- [X] calibre

* TODO [0/2] Campana espaces des cycles compact   :REFERENCE:CALIBRE:FULLBIB:
[2016-07-06 mer. 11:54]

- [ ] full
- [ ] calibre

*Ne traite pas directement du cas hyperkahlérien*
 
#+BEGIN_SRC BIBTEX
@article {MR999456,
    AUTHOR = {Campana, Fr{\'e}d{\'e}ric},
     TITLE = {Espaces de twisteurs dont l'espace des cycles a ses
              composantes irr\'eductibles compactes},
   JOURNAL = {C. R. Acad. Sci. Paris S\'er. I Math.},
  FJOURNAL = {Comptes Rendus des S\'eances de l'Acad\'emie des Sciences.
              S\'erie I. Math\'ematique},
    VOLUME = {308},
      YEAR = {1989},
    NUMBER = {19},
     PAGES = {565--568},
      ISSN = {0249-6291},
     CODEN = {CASMEI},
   MRCLASS = {32G10 (32J10 32L25 53C21)},
  MRNUMBER = {999456},
}
#+END_SRC

* TODO [0/2] Cycle Spaces, Several complex variables VII          :REFERENCE:
[2016-07-06 mer. 12:03]

- [ ] full
- [ ] calibre


#+BEGIN_SRC BIBTEX
@incollection {MR1326625,
    AUTHOR = {Campana, F. and Peternell, Th.},
     TITLE = {Cycle spaces},
 BOOKTITLE = {Several complex variables, {VII}},
    SERIES = {Encyclopaedia Math. Sci.},
    VOLUME = {74},
     PAGES = {319--349},
 PUBLISHER = {Springer, Berlin},
      YEAR = {1994},
   MRCLASS = {32G10 (32F10)},
  MRNUMBER = {1326625},
       DOI = {10.1007/978-3-662-09873-8_9},
       URL = {http://dx.doi.org/10.1007/978-3-662-09873-8_9},
}
#+END_SRC

* TODO [0/3] Espace des twisteurs de classe $C$                   :REFERENCE:
[2016-07-06 mer. 18:22]


- [ ] full
- [ ] calibre
- [ ] Téléchargé

*là où il prouve que C n'est jamais compact dans le cas HK*

#+BEGIN_SRC BIBTEX
@article {MR1094468,
    AUTHOR = {Campana, F.},
     TITLE = {On twistor spaces of the class {$\scr C$}},
   JOURNAL = {J. Differential Geom.},
  FJOURNAL = {Journal of Differential Geometry},
    VOLUME = {33},
      YEAR = {1991},
    NUMBER = {2},
     PAGES = {541--549},
      ISSN = {0022-040X},
     CODEN = {JDGEAS},
   MRCLASS = {32L25 (32J20 53C25)},
  MRNUMBER = {1094468},
MRREVIEWER = {S. M. Salamon},
       URL = {http://projecteuclid.org/euclid.jdg/1214446329},
}
#+END_SRC

